name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Prepare and Test

    runs-on: ubuntu-latest
    
    env:
      TEST_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    services:
      telegram-bot-api:
        image: huntechio/telegram-bot-api:master-7cf91e4
        ports:
          - 8081:8081
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run Tests
      run: |
        make test

    - name: Send Coveralls report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
